package com.mycompany.zipper;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.*;
import javax.swing.SwingWorker;


public class ProcessingDialog extends javax.swing.JDialog {

    private List<String> inputFilenames;
    private String outputFilename;
    private final String folderPath;
    private final FileZipper fileZipperWorker;
    
    class FileZipper extends SwingWorker<Void, Void> {

        private final static int BUFFER_SIZE = 4096;
        
        // Objeto para referenciar a los archivos que queremos comprimir
        private BufferedInputStream origin = null;
        // Objeto para referenciar el archivo zip de salida
        private ZipOutputStream out = null;
        
        @Override
        protected Void doInBackground() throws Exception {
            try {
                out = new ZipOutputStream(
                    new BufferedOutputStream(
                            new FileOutputStream(outputFilename)));

                // Buffer de transferencia para almacenar datos a comprimir
                byte[] data = new byte[BUFFER_SIZE];
                
                int i = 0;
                int N = inputFilenames.size();
                for (String filename : inputFilenames) {
                    FileInputStream fi = new FileInputStream(folderPath + "\\" + filename);
                    origin = new BufferedInputStream(fi, BUFFER_SIZE);
                    ZipEntry entry = new ZipEntry( filename );
                    out.putNextEntry( entry );
                    // Leemos datos desde el archivo origen y se envían al archivo destino
                    int count;
                    while((count = origin.read(data, 0, BUFFER_SIZE)) != -1)
                    {
                        if(this.isCancelled()){
                            origin.close();
                            out.close();
                            return null;
                        }
                        out.write(data, 0, count);
                    }
                    // Cerramos el archivo origen, ya enviado a comprimir
                    origin.close();
                    progressBar.setValue((int) (++i * 100.0) / N);
                }
                
            } catch (IOException e){
                e.printStackTrace();
            } finally {
                // Cerramos el archivo zip
                out.close();
                origin.close();
            }
            return null;
        }
        
        @Override
        protected void done(){
            if(this.isCancelled()){
                new File(ProcessingDialog.this.outputFilename).delete();
            }
            ProcessingDialog.this.dispose();
        }
    }
    
    /**
     * Creates new form ProcessingDialog
     */
    public ProcessingDialog(java.awt.Frame parent, boolean modal, String folderPath,
            List<String> inputFilenames, String outputFilename) {
        super(parent, modal);
        initComponents();
        
        this.folderPath = folderPath;
        this.inputFilenames = inputFilenames;
        // ensures that the output file has .zip extension
        if(outputFilename.endsWith(".zip")){
            this.outputFilename = outputFilename;
        } else {
            this.outputFilename = outputFilename + ".zip";
        }
        
        this.setVisible(true);
        this.fileZipperWorker = new FileZipper();
        this.fileZipperWorker.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comprimiendo ficheros");

        progressBar.setStringPainted(true);

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.fileZipperWorker.cancel(true);
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
